# Utiliser une image Node officielle
FROM node:20

# Installer Ionic CLI globalement
RUN npm install -g @ionic/cli

# Définir le répertoire de travail
WORKDIR /app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du projet
COPY . .

# Exposer le port de développement Ionic (par défaut 8100)
EXPOSE 8100

# Commande par défaut pour lancer le serveur de dev
CMD ["ionic", "serve", "--host", "0.0.0.0", "--port", "8100"]
